### PR TITLE
Rel-lang-url

### PR DESCRIPTION
**Pull request by Andygol**
Implemented a link decorator feature that automatically converts links within documents to localized ones. This enhancement eliminates the need for manually appending language codes to the links.

### CODE REVIEW

**Review by Andygol — COMMENTED** [review]
RE https://github.com/kubernetes/website/issues/18403

**Comment by Andygol** [comment]
📝 Note

- [x] The [render-link.html](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/_markup/render-link.html)  template is provided by Hugo for inspiration.

**Comment by Andygol** [comment]
There is a big question: how to check the presence of a localized document using the capabilities of Hugo, for further use in the [link decorator (render-link.html)](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/_markup/render-link.html)?

```mermaid
graph LR;

src_link("Link in a doc…")


src_link-->none_localized_link("… is not localized\n starts with `/…`")-->
check_for_localization{"if a localized\ndoc exists"}-- "yes, it is" -->add_lng_prefix("Add lang-code\nprefix to the link")

src_link-->indoc_link("… is in the same doc\nstarts with`#` symbol")
src_link-->already_localized_link("… is already localized\n starts with\n`/lang-code/…`")
src_link-->ext_link("…is an external link\nstarts with protocol\n [https:|mailto:|…] ")

ext_link & already_localized_link & indoc_link ---> asis("Keep it as is")
check_for_localization-- "no, it isn't" -->asis
```

**Comment by sftim** [comment]
If you open this against k/website, you'll get more eyeballs for feedback. You can then copy the fix to this fork.

**Comment by Andygol** [comment]
Depends on: https://github.com/kubernetes/website/pull/47612 - Fixed flag deprecations and updated Hugo version to latest

**Comment by Andygol** [comment]
The current approach fully implements the logic of link decoration by adding a language prefix to localised documents where it is not explicitly specified. Links with a hard-coded https://kubernetes.io/ or https://k8s.io/ are considered external and processed as such, even if there are localised versions of the link in the documentation. Handling such cases significantly complicates the code and processing time, and it is easier to correct such links directly in the text of documents.

**Comment by Andygol** [comment]
https://github.com/kubernetes/website/pull/47620 - already in main

**Pull request closed without merging**
